/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : d:/Dropbox/saccubus/Saccubus/src/nekomata/parser\\niwango.g
 *     -                            On : 2013-06-10 19:55:13
 *     -                for the parser : niwangoParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
niwangoParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pniwangoParser, which is returned from a call to niwangoParserNew().
 *
 * The methods in pniwangoParser are  as follows:
 *
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->program(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr6(pniwangoParser)
 *  - 
 niwangoParser_assign_op_return
      pniwangoParser->assign_op(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr5(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr4(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr3(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr2(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->expr1(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->term(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->postfix(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->primary(pniwangoParser)
 *  - 
 shared_ptr<const ObjectNode>
      pniwangoParser->object_def(pniwangoParser)
 *  - 
 niwangoParser_object_element_return
      pniwangoParser->object_element(pniwangoParser)
 *  - 
 shared_ptr<const ExprNode>
      pniwangoParser->object_expr_list(pniwangoParser)
 *  - 
 niwangoParser_name_return
      pniwangoParser->name(pniwangoParser)
 *  - 
 shared_ptr<const ObjectNode>
      pniwangoParser->array(pniwangoParser)
 *  - 
 shared_ptr<const LiteralNode>
      pniwangoParser->literal(pniwangoParser)
 *  - 
 shared_ptr<const BoolLiteralNode>
      pniwangoParser->boolean(pniwangoParser)
 *  - 
 shared_ptr<const NumericLiteralNode>
      pniwangoParser->numeric(pniwangoParser)
 *  - 
 shared_ptr<const StringLiteralNode>
      pniwangoParser->string(pniwangoParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_niwangoParser_H
#define _niwangoParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#undef __cplusplus


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct niwangoParser_Ctx_struct niwangoParser, * pniwangoParser;



#include <string>
#include <iostream>
#include <memory>
#include <cstdlib>
#include <cinamo/String.h>
#include "ParseUtil.h"
#include "../tree/Node.h"
using namespace nekomata::parser::util;
using namespace nekomata::tree;
using std::shared_ptr;
typedef pANTLR3_COMMON_TOKEN Token;


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif
typedef struct niwangoParser_assign_op_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    std::string result;
    Token token;
}
    niwangoParser_assign_op_return;



typedef struct niwangoParser_object_element_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    bool hasName;
    std::string name;
    shared_ptr<const ExprNode> exprNode;
}
    niwangoParser_object_element_return;



typedef struct niwangoParser_name_return_struct
{
    /** Generic return elements for ANTLR3 rules that are not in tree parsers or returning trees
     */
    pANTLR3_COMMON_TOKEN    start;
    pANTLR3_COMMON_TOKEN    stop;
    std::string result;
    Token token;
}
    niwangoParser_name_return;





/** Context tracking structure for 
niwangoParser

 */
struct niwangoParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     shared_ptr<const ExprNode>
     (*program)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr6)	(struct niwangoParser_Ctx_struct * ctx);

     niwangoParser_assign_op_return
     (*assign_op)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr5)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr4)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr3)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr2)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*expr1)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*term)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*postfix)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*primary)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ObjectNode>
     (*object_def)	(struct niwangoParser_Ctx_struct * ctx, Token tok);

     niwangoParser_object_element_return
     (*object_element)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ExprNode>
     (*object_expr_list)	(struct niwangoParser_Ctx_struct * ctx);

     niwangoParser_name_return
     (*name)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const ObjectNode>
     (*array)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const LiteralNode>
     (*literal)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const BoolLiteralNode>
     (*boolean)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const NumericLiteralNode>
     (*numeric)	(struct niwangoParser_Ctx_struct * ctx);

     shared_ptr<const StringLiteralNode>
     (*string)	(struct niwangoParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct niwangoParser_Ctx_struct * ctx);
    void	    (*free)   (struct niwangoParser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pniwangoParser niwangoParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API pniwangoParser niwangoParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define T__52      52
#define T__53      53
#define T__54      54
#define T__55      55
#define T__56      56
#define COMMENT      4
#define DIGIT      5
#define EOL      6
#define ESC_SEQ      7
#define EXPONENT      8
#define HEX_DIGIT      9
#define HEX_LITERAL      10
#define IDENT      11
#define LETTER      12
#define NONZERO_DIGIT      13
#define NUM_LITERAL      14
#define OCT_DIGIT      15
#define OCT_LITERAL      16
#define STRING_DOUBLE      17
#define STRING_DOUBLE_ELEMENT      18
#define STRING_SINGLE      19
#define STRING_SINGLE_ELEMENT      20
#define WS      21
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for niwangoParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
